#6-73 docker-compose to automate lengthy docker run command using volumes inter alia
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # web as server/container name - build context (. - could be path) pwd with custom Dockerfile name
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
      # (1) do *not* try to map a folder against /app/node_modules in the container;
      # (2) map current working directory (outside container):/app folder in container